### ISSUE TITLE
Error table expected on character login

### ISSUE THREAD

**Issue by jdmaddison** [Jaliborc/PetTracker#98]
**Running Software (please complete the following information):**
 - Build 8.0.1.2717843
 - 8.0.6

**Have you read the changelog? (please don't waste our time)**
Yes.

**Describe the bug**
Error detected by Swatter on character login.

**Expected behavior**
Not to get error.

**Error Logs**

Date: 2018-09-22 10:04:48
ID: 1
Error occured in: Global
Count: 1
Message: ...erface\AddOns\PetTracker\Features\BattleListener.lua line 39:
   bad argument #1 to 'pairs' (table expected, got nil)
Debug:
   [C]: pairs()
   ...erface\AddOns\PetTracker\Features\BattleListener.lua:39: Upgrade()
   ...erface\AddOns\PetTracker\Features\BattleListener.lua:30: ?()
   PetTracker\PetTracker.lua:40: ForAllModules()
   PetTracker\PetTracker.lua:54: ?()
   PetTracker\PetTracker.lua:21:
      PetTracker\PetTracker.lua:21
Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**To Reproduce**

Login with LUA error displayed.

**Comment by smeeckaert** [comment]
Corrected by #99

**Comment by jdmaddison** [comment]
Those recent changes have not been committed to whatever branch (terminology unclear) is being downloaded from Twitch. So, this error remains, even with a clean install.
